2024-05-23 18:16:04,276 ERROR libqtile start.py:start():L111 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/scripts/start.py", line 109, in start
    q.loop()
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 202, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 227, in async_loop
    self.load_config(initial=True)
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 139, in load_config
    self._process_screens(reloading=not initial)
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 403, in _process_screens
    scr._configure(self, i, x, y, w, h, grp, reconfigure_gaps=reconfigure_gaps)
  File "/usr/lib/python3.12/site-packages/libqtile/config.py", line 477, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/usr/lib/python3.12/site-packages/libqtile/bar.py", line 342, in _configure
    if i.configured and i.__class__.__name__ != "Mirror":
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'configured'
